# Site settings
title: Untitled
email: bcvanduuren@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website will mainly be used as my online memory, meaning
  It'll mostly contain stuff I did and/or learned.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://boyvanduuren.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  boyvanduuren

# Build settings
markdown: kramdown
